# Scanner Scripts ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bd-selfscan.name" . }}-scanner-scripts
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bd-selfscan.labels" . | nindent 4 }}
    app.kubernetes.io/component: scanner-scripts
  annotations:
    description: "Scanner scripts for BD SelfScan container vulnerability scanning"
    bd-selfscan/config-type: "scripts"
data:
  # Core scanning engine
  bdsc-container-scan.sh: |
    {{- .Files.Get "scripts/bdsc-container-scan.sh" | nindent 4 }}
  
  # Single application wrapper
  scan-application.sh: |
    {{- .Files.Get "scripts/scan-application.sh" | nindent 4 }}
  
  # Bulk application scanner
  scan-all-applications.sh: |
    {{- .Files.Get "scripts/scan-all-applications.sh" | nindent 4 }}
  
  # Utility functions
  common-functions.sh: |
    {{- .Files.Get "scripts/common-functions.sh" | nindent 4 }}
