apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "bd-selfscan.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace }}
    app.kubernetes.io/component: system
  annotations:
    description: "Black Duck SelfScan system namespace for multi-application container scanning"
    bd-selfscan/managed-by: "helm"
    bd-selfscan/purpose: "container-scanning"